"""Atomic, pickle-free persistence for mapping snapshots."""

from datetime import datetime, timezone
import json
import os
from pathlib import Path
import shutil
import tempfile
from typing import Dict, Mapping, Tuple

import numpy as np

from .grid_map import occupancy_to_pgm


SNAPSHOT_SCHEMA_VERSION = 1
# ROS map_server trinary conventions. Pixel 205 represents occupancy
# 50/255 ~= 0.196078, which must remain strictly above free_thresh.
MAP_SERVER_FREE_THRESHOLD = 0.196
MAP_SERVER_OCCUPIED_THRESHOLD = 0.65


def _sync_file(path: Path) -> None:
    with path.open("rb") as stream:
        os.fsync(stream.fileno())


def _write_binary_ply(
    path: Path, points: np.ndarray, colors_rgb: np.ndarray = None
) -> None:
    xyz = np.ascontiguousarray(points, dtype="<f4")
    if xyz.ndim != 2 or xyz.shape[1] != 3 or not np.isfinite(xyz).all():
        raise ValueError("PLY points must be a finite N-by-3 array")
    colors = None
    if colors_rgb is not None:
        colors = np.asarray(colors_rgb)
        if colors.shape != xyz.shape or not np.isfinite(colors).all():
            raise ValueError("PLY colors must be a finite N-by-3 array")
        if (colors < 0).any() or (colors > 255).any():
            raise ValueError("PLY colors must be in [0, 255]")
        colors = np.rint(colors).astype(np.uint8)
    color_header = (
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n"
        if colors is not None
        else ""
    )
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment generated by go2_mapping\n"
        "element vertex {}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "{}"
        "end_header\n"
    ).format(xyz.shape[0], color_header)
    with path.open("wb") as stream:
        stream.write(header.encode("ascii"))
        if colors is None:
            stream.write(xyz.tobytes())
        else:
            records = np.empty(
                xyz.shape[0],
                dtype=[
                    ("x", "<f4"),
                    ("y", "<f4"),
                    ("z", "<f4"),
                    ("red", "u1"),
                    ("green", "u1"),
                    ("blue", "u1"),
                ],
            )
            records["x"] = xyz[:, 0]
            records["y"] = xyz[:, 1]
            records["z"] = xyz[:, 2]
            records["red"] = colors[:, 0]
            records["green"] = colors[:, 1]
            records["blue"] = colors[:, 2]
            stream.write(records.tobytes())
        stream.flush()
        os.fsync(stream.fileno())


def _write_npz(
    path: Path,
    voxel_state: Mapping[str, np.ndarray],
    grid_state: Mapping[str, np.ndarray],
    metadata: Mapping[str, object],
) -> None:
    arrays: Dict[str, np.ndarray] = {}
    arrays.update({key: np.asarray(value) for key, value in voxel_state.items()})
    arrays.update({key: np.asarray(value) for key, value in grid_state.items()})
    arrays["metadata_json"] = np.asarray(
        json.dumps(metadata, sort_keys=True, separators=(",", ":"))
    )
    with path.open("wb") as stream:
        np.savez_compressed(stream, **arrays)
        stream.flush()
        os.fsync(stream.fileno())


def save_snapshot(
    output_dir: str,
    voxel_state: Mapping[str, np.ndarray],
    grid_state: Mapping[str, np.ndarray],
    occupancy: np.ndarray,
    origin_x: float,
    origin_y: float,
    resolution: float,
    metadata: Mapping[str, object],
    free_threshold: int = 25,
    occupied_threshold: int = 65,
) -> Path:
    """Publish a complete snapshot directory with one atomic rename.

    The final directory is never visible in a partially-written state.  Files
    inside it are ``map.ply``, ``map.pgm``, ``map.yaml``, and ``state.npz``.
    """

    root = Path(output_dir).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    if not root.is_dir():
        raise ValueError("output_dir is not a directory")

    metadata_copy = dict(metadata)
    metadata_copy["schema_version"] = SNAPSHOT_SCHEMA_VERSION
    metadata_copy["saved_at_utc"] = datetime.now(timezone.utc).isoformat()
    metadata_copy["grid_origin"] = [float(origin_x), float(origin_y), 0.0]
    metadata_copy["grid_resolution"] = float(resolution)

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S_%fZ")
    final_dir = root / ("go2_map_" + stamp)
    temporary_dir = Path(tempfile.mkdtemp(prefix=".go2_map_tmp_", dir=str(root)))
    try:
        _write_binary_ply(
            temporary_dir / "map.ply",
            voxel_state["voxel_centroids"],
            voxel_state.get("voxel_colors"),
        )
        pgm = occupancy_to_pgm(
            occupancy,
            free_threshold=free_threshold,
            occupied_threshold=occupied_threshold,
        )
        pgm_path = temporary_dir / "map.pgm"
        with pgm_path.open("wb") as stream:
            stream.write(pgm)
            stream.flush()
            os.fsync(stream.fileno())

        yaml_text = (
            "image: map.pgm\n"
            "mode: trinary\n"
            "resolution: {:.12g}\n"
            "origin: [{:.12g}, {:.12g}, 0.0]\n"
            "negate: 0\n"
            "occupied_thresh: {:.12g}\n"
            "free_thresh: {:.12g}\n"
        ).format(
            float(resolution),
            float(origin_x),
            float(origin_y),
            MAP_SERVER_OCCUPIED_THRESHOLD,
            MAP_SERVER_FREE_THRESHOLD,
        )
        yaml_path = temporary_dir / "map.yaml"
        with yaml_path.open("w", encoding="utf-8") as stream:
            stream.write(yaml_text)
            stream.flush()
            os.fsync(stream.fileno())

        _write_npz(
            temporary_dir / "state.npz", voxel_state, grid_state, metadata_copy
        )
        directory_fd = os.open(str(temporary_dir), os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
        os.replace(str(temporary_dir), str(final_dir))
        root_fd = os.open(str(root), os.O_RDONLY)
        try:
            os.fsync(root_fd)
        finally:
            os.close(root_fd)
    except Exception:
        if temporary_dir.exists():
            shutil.rmtree(str(temporary_dir))
        raise
    return final_dir


def load_snapshot(path: str) -> Tuple[Dict[str, np.ndarray], Dict[str, object]]:
    """Load arrays and JSON metadata from a snapshot NPZ without pickle."""

    state_path = Path(path).expanduser().resolve()
    if state_path.is_dir():
        state_path = state_path / "state.npz"
    if not state_path.is_file():
        raise FileNotFoundError(str(state_path))
    if state_path.stat().st_size > 2147483648:
        raise ValueError("state file exceeds the 2 GiB safety limit")

    required = {
        "voxel_keys",
        "voxel_centroids",
        "voxel_counts",
        "voxel_last_seen_ns",
        "grid_keys",
        "grid_log_odds",
        "grid_last_seen_ns",
        "grid_last_robot_cell",
        "metadata_json",
    }
    optional = {"voxel_colors", "voxel_color_counts", "voxel_variances"}
    with np.load(str(state_path), allow_pickle=False) as archive:
        missing = required.difference(archive.files)
        if missing:
            raise ValueError("state file is missing: " + ", ".join(sorted(missing)))
        arrays = {
            key: np.asarray(archive[key]).copy()
            for key in required.union(optional.intersection(archive.files))
            if key != "metadata_json"
        }
        raw_metadata = archive["metadata_json"]
        if raw_metadata.shape != ():
            raise ValueError("metadata_json must be a scalar")
        metadata = json.loads(str(raw_metadata.item()))
    if not isinstance(metadata, dict):
        raise ValueError("snapshot metadata must be a JSON object")
    if int(metadata.get("schema_version", -1)) != SNAPSHOT_SCHEMA_VERSION:
        raise ValueError("unsupported snapshot schema version")
    return arrays, metadata
